# Generated by Django 3.2 on 2022-09-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsapp', '0002_alter_course_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.ImageField(upload_to=''),
        ),
    ]
